version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: diabetes_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: diabetes_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: diabetes_backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgres://user:password@db:5432/diabetes_db
      JWT_SECRET: your_super_secret_key
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: diabetes_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api # Or your backend service name if using docker network properly
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
